### ISSUE TITLE
Setting to Synchronize open Frames

### ISSUE THREAD

**Issue by jhsa** [NaturalDevCR/MyUiPro#6]
It would be nice if the open Frames could be synchronized. For example, Frame 1 with the main mix, and another with the EQ Edit. When we select a different channel in one frame, the other would follow..
You could make this setting selectable/optional..
Thanks.

**Comment by NaturalDevCR** [comment]
I'll add it to the checklist, sounds like a good feature to have.

**Comment by NaturalDevCR** [comment]
So I've been trying to find a way to sync the frames programatically, my best guess was to add the `SYNC_ID` as a url param, but nothing worked.

But, it is posible to do it, just by following the Soundcraft instructions as you would do with multiple browsers or tabs, you just need to turn on the channel sync setting in Settings => Local => Channel Sync, and set the SYNC_ID on each frame as you prefer to.

So, unless someone finds a way to set this as an URL param for the iframe, I see no other way to do it, but with the traditional way.

The downside with the app, is that seems like when you reload, every frame will take the same SYNC_ID and all of them will be syncronized together, which is bad news if you want to have multiple syncronizations.
